#include <stdlib.h>
#include <stdio.h>
#include <locale.h>
#include <strings.h>

int main(){

    setlocale(LC_ALL, "Portuguese");

    char palavra[255]; //UMA PALAVRA SÃO VARIAS LETRAS QUE, SEGUIDAS UMAS DAS OUTRAS, A FORMAM //10 = TAMANHO MÁXIMO

    //STDIN É UM TIPO DE PONTEIRO PARA UM ARQUIVO ABERTO PELO PROGRAMA, PARA A ENTRADA DE DADOS DO USUÁRIO //EXISTE TAMBÉM STDOUT PARA SAIDA E STDERR PARA ERROS
    //BUFFER É UM LOCAL QUE SERVE DE PONTE TEMPORÁRIA PARA OS DADOS //COMUMENTE ALGUM DADO PERMANECE NO BUFFER, COMO AO TECLARMOS "ENTER" QUE É "\N" PARA O PROGRAMA, E A ISSO CHAMAM DE "SUJEIRA"
    //ESTA SUJEIRA DEVE SER LIMPA, PARA O FUNCIONAMENTO CORRETO DO BUFFER, POIS ANTER DE LER O PRÓXIMO DADO INSERIDO PELO USUÁRIO, ELE IRÁ LER A SUJEIRA

    //O SETBUF ESCRITO É UMA FORMA DE LIMPAR A SUJEIRA(DE ENTRADA, POIS É BUF DO STDIN)
    //FGETS SERVE PARA LER UM FLUXO DE CARACTERES

    //STRLEN DESCOBRE O TAMANHO DA PRÓPRIA STRING/PALAVRA
    //NESTE CASO O TAMANHO MÁXIMO É DE 10 LETRAS, MAS SE A PALAVRA TIVER MENOS QUE 10 LETRAS, AS OUTRAS POSIÇÕES RESTANTES, VAZIAS, OCUPARÃO ESPAÇO NA MEMÓRIA
    //A MÁQUINA INTERPRETA A ULTIMA POSIÇÃO DO VETOR DE STRINGS, O FIM DO FLUXO MÁXIMO, PONDO NELA -NA ULTIMA POSIÇÃO- UM /0
    //ENTÃO PARA NÃO HAVER DISPERDICIO DE MEMORIA, TEMOS QUE DESLOCAR O /0 PARA A POSIÇÃO POSTERIOR AO ULTIMO CARACTER DA PALAVRA DIGITADA


    printf("Digite uma palavra: \n");

    //LIMPAR SUJEIRA
    setbuf(stdin, 0);

    //LEITURA DO FLUXO DE CARACTERES, SENDO SUA LÓGICA: VARIÁVEL, TAMANHO MÁXIMO, ARQUIVO DE ENTRADA
    fgets(palavra, 255, stdin);

    //ELIMINAÇÃO DAS CASAS NÃO USADAS
    palavra[strlen(palavra) - 1] = '\0'; //DEFINIÇÃO DA ÚLTIMA POSIÇÃO DA PALAVRA COMO SENDO ÚLTIMA USADA E QUE DEVE SER CONSIDERADA

    //IMPRESSÃO DO NUMERO DE CASAS DA PALAVRA E IMPRESSAO DA PALAVRA
    printf("O tamanho da palavra digitada, em termos de posições utilizadas, é: %d\n", strlen(palavra) - 1); //MENOS UM, PORQUE CONTA O 0

    printf("%s\n", palavra);

    system("pause");
    return 0;
    }

