#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <stdbool.h>
#include <time.h> //utilização como referencial do tempo cronometrado no computador

int main(){

    setlocale(LC_ALL, "Portuguese");

    //TEMOS QUE ENTENDER QUE NA COMPUTAÇÃO NÃO EXISTE ALEATORIEDADE PURA
    //UM NÚMERO DITO COMO ALEATÓRIO, É NA VERDADE O PRODUTO DE UMA EQUAÇÃO PRÉ-DEFINIDA
    //OS NUMEROS QUE COMPOEM ESTA EQUAÇÃO SÃO ESCOLHIDOS POR UM FATOR DEFINIDO TAMBÉM, SENDO PORTANTO O SEU RESULTADO PRÉ-DEFINIDO, E NÃO LITERALMENTE "ALEATORIO"
    //O FATOR QUE IRÁ DEFINIR O DESENROLAR DA FUNÇÃO É CHAMADO DE "SEMENTE"
    //NOSSA SEMENTE TERÁ COMO REFERENCIAL O TEMPO DO COMPUTADOR, QUE ESTÁ SEMPRE MUDANDO, SENDO PORTANTO A SEMENTE CONSTANTEMENTE ALTERADA, O QUE PRODUZ A "ALEATORIEDADE" DO RESULTADO DA EQUAÇÃO

    srand((unsigned)time(NULL)); //UNSIGNED = INTERVALO DE NUMEROS POSITIVOS, TIME(NULL)) = RELÓGIO DO COMPUTADOR //ESTUDAR A CORRELAÇÃO
    int x = ((rand() % 6) + 1); //RAND É UM INTERVALO DE NUMEROS ENTRE 0 E 32767 //RAND % 6 PRODUZ NUMEROS ALEATORIOS ENTRE 0 E 5 //RAND % 6 + 1 PRODUZ NUMEROS ALEATORIOS ENTRE 1 E 6

    printf("Numero aleatorio de 1 a 6: %d\n", x);



 system("pause");
 return 0;

 }
